### ISSUE TITLE
BUG - 403 forbidden when member cannot be messaged

### ISSUE THREAD

**Issue by Xarlos89** [Xarlos89/ZorakBot#160]
```
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/src/cogs/admin/verification_on_join.py", line 46, in on_member_join
    await member.send(welcome_message)
  File "/usr/local/lib/python3.9/site-packages/discord/abc.py", line 1616, in send
    data = await state.http.send_message(
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 365, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50007): Cannot send messages to this user
Ignoring exception in on_member_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/src/cogs/logging/logging_member_roles.py", line 47, in on_member_update
    await logs_channel.send(embed=embed)
UnboundLocalError: local variable 'embed' referenced before assignment
```
Error appears to block verification. Occurs when a user who has "Open DM permission" off, and the user cannot be messaged.

Perhaps we can add an error handler here that skips the message if someone cannot be DM-ed.

**Comment by Xarlos89** [comment]
https://github.com/practical-python-org/ZorakBot/pull/174
