### ISSUE TITLE
BUG - on_message_delete error

### ISSUE THREAD

**Issue by Xarlos89** [Xarlos89/ZorakBot#162]
```
2023-08-24 11:53:23,298 INFO cogs.admin.admin_startup Started at: {2023-08-24 11:53:23.298241}
2023-08-24 11:53:23,299 INFO cogs.admin.admin_startup Greetings, puny earth-creature.
Ignoring exception in on_message_delete
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/src/cogs/logging/logging_message_delete.py", line 68, in on_message_delete
    await logs_channel.send(f"{username.mention}", embed=embed)
  File "/usr/local/lib/python3.9/site-packages/discord/abc.py", line 1616, in send
    data = await state.http.send_message(
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 371, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.thumbnail.url: Not a well formed URL.
```
Appears to happen when a thumbnail is sent with the embed? Not sure why. Should look into the message_delete logging cog.

**Comment by Xarlos89** [comment]
```
Ignoring exception in on_user_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/src/cogs/logging/logging_avatars.py", line 27, in on_user_update
    await logs_channel.send(embed=embed)
  File "/usr/local/lib/python3.9/site-packages/discord/abc.py", line 1616, in send
    data = await state.http.send_message(
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 371, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.thumbnail.url: Not a well formed URL.
```
Also appears to be happening in logging_avatars.py

**Comment by Xarlos89** [comment]
```
Ignoring exception in on_member_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/src/cogs/logging/logging_member_roles.py", line 47, in on_member_update
    await logs_channel.send(embed=embed)
UnboundLocalError: local variable 'embed' referenced before assignment
```

... and also in logging_member_roles.py
