### ISSUE TITLE
BUG - Logging: Message_edit throws error when text is too long

### ISSUE THREAD

**Issue by Xarlos89** [Xarlos89/ZorakBot#77]
`Ignoring exception in on_message_edit
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "/src/cogs/logging_message_edit.py", line 44, in on_message_edit
    await logs_channel.send(f"{username.mention}", embed=embed)
  File "/usr/local/lib/python3.9/site-packages/discord/abc.py", line 1606, in send
    data = await state.http.send_message(
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 366, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.0.value: Must be 1024 or fewer in length.
In embeds.0.fields.1.value: Must be 1024 or fewer in length.
`

Message edits that are more than 1024 characters throw an error. This can be handled by breaking the text into blocks of 1024 chars, and adding new feilds for every block.

**Comment by Xarlos89** [comment]
Fixed in #319
