### ISSUE TITLE
/ticket broken

### ISSUE THREAD

**Issue by Xarlos89** [Xarlos89/ZorakBot#81]
When creating a ticket, an error is thrown:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/ui/view.py", line 414, in _scheduled_task
    await item.callback(interaction)
  File "/src/cogs/general_tickets.py", line 30, in button_callback
    support = await self.bot.fetch_channel(mod_channel["server_support"])
AttributeError: 'make_a_ticket' object has no attribute 'bot'`

and the ticket is not created

**Comment by Xarlos89** [comment]
Fixed with https://github.com/practical-python-org/ZorakBot/pull/82
